# Generated by Django 2.2.4 on 2019-08-07 08:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cookapp', '0002_auto_20190806_0059'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
            ],
        ),
        migrations.RemoveField(
            model_name='ingredient',
            name='code',
        ),
        migrations.AddField(
            model_name='recipe',
            name='content',
            field=models.TextField(default='sample_context'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='category',
            field=models.ForeignKey(default=9999, on_delete=django.db.models.deletion.CASCADE, to='cookapp.Category'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='name',
            field=models.CharField(default='test_name', max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='recipe',
            name='image',
            field=models.ImageField(blank=True, default='test_image', upload_to='images/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='recipe',
            name='name',
            field=models.CharField(default='test_name', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='recipe',
            name='url',
            field=models.URLField(default='test_url'),
            preserve_default=False,
        ),
    ]
