# Generated by Django 2.2.4 on 2019-08-07 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cookapp', '0003_auto_20190807_1724'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='see',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recipe',
            name='time',
            field=models.CharField(default='20min', max_length=10),
            preserve_default=False,
        ),
    ]
